### ISSUE TITLE
getCardId

### ISSUE THREAD

**Issue by aorgish** [rogoff/rolling-scopes-js-assignments#8]
https://github.com/rogoff/rolling-scopes-js-assignments/blob/98a5b0da2e13c9dbdba0d64ad254e42cccdfe837/task/01-strings-tasks.js#L276-L277

Удалось таки запутать с '10' . :)
Больше же ни одна карта не начинается на '1', поэтому можно сделать просто:

```
 return ... + 'A234567891JQK'.indexOf(value[0]);
```

**Comment by YauheniRohau** [comment]
я не специально) думал T - ten будет понятно))) спасибо за переревью)
